# username elastic
# password 123456
#IP=192.168.88.250:9200


GET 192.168.88.250:9200/_cat/indices
Authorization: Basic ZWxhc3RpYzoxMjM0NTY=

####

GET 192.168.88.250:9200/ferrumgate-audit/_mapping
Authorization: Basic ZWxhc3RpYzoxMjM0NTY=

####

DELETE  192.168.88.250:9200/ferrumgate-audit
Authorization: Basic ZWxhc3RpYzoxMjM0NTY=


####

GET 192.168.88.250:9200/ferrumgate-audit/_search
Authorization: Basic ZWxhc3RpYzoxMjM0NTY=

###

POST 192.168.88.250:9200/ferrumgate-audit/_search
Authorization: Basic ZWxhc3RpYzoxMjM0NTY=
Content-Type: application/json

{
    "query": {
      "match_all": {}
    }
}

###
POST 192.168.88.250:9200/ferrumgate-audit/_search
Authorization: Basic ZWxhc3RpYzoxMjM0NTY=
Content-Type: application/json

{
    "from": 0,
    "size": 10,
    "sort": {
        "insertDate": "desc"
    },
    "query": {
        "bool": {
            "must": [
                {
                    "range": {
                        "insertDate": {
                            "gte": "1901-01-31T22:03:04.000Z",
                            "lt": "2022-12-15T16:29:17.901Z"
                        }
                    }
                }
            ]
        }
    }
}


####

POST 192.168.88.250:9200/ferrumgate-audit/_search
Authorization: Basic ZWxhc3RpYzoxMjM0NTY=
Content-Type: application/json

{
    "from": 0,
    "size": 10,
    "sort": {
        "insertDate": "desc"
    },
    "query": {
        "bool": {
            "must": [
                {
                    "range": {
                        "insertDate": {
                            "gte": "1901-01-31T22:03:04.000Z",
                            "lt": "2022-11-15T16:53:58.954Z"
                        }
                    }
                },
                {
                    "bool": {
                        "should": [
                            {
                                "term": {
                                    "username": "test@test.com"
                                }
                            },
                             {
                                "term": {
                                    "username": "test2@test.com"
                                }
                            }
                        ]
                    }
                }
            ]
        }
    }
}


####
GET 192.168.88.250:9200/_cat/indices
Authorization: Basic ZWxhc3RpYzoxMjM0NTY=

####
GET https://192.168.88.250:9200/ferrumgate-activity-20221117/_search
Authorization: Basic ZWxhc3RpYzoxMjM0NTY=

####

DELETE  192.168.88.250:9200/ferrumgate-audit
Authorization: Basic ZWxhc3RpYzoxMjM0NTY=

###

POST https://192.168.88.250:9200/ferrumgate-activity-*/_search
Authorization: Basic ZWxhc3RpYzoxMjM0NTY=
Content-Type: application/json

{
    "from": 0,
    "size": 10,
    "sort": {
        "insertDate": "desc"
    },
    "query": {
        "bool": {
            "must": [
                {
                "query_string": {
                    "query": "12345*",
                    "fields": ["requestId", "type", "authSource", "ip", "statusMessage",
                        "username", "userId", "gatewayId", "gatewayName", "networkId", "networkName"]
                }
            }
            ]
        }
    }
}

####
POST https://192.168.88.250:9200/ferrumgate-activity-*/_search
Authorization: Basic ZWxhc3RpYzoxMjM0NTY=
Content-Type: application/json

{"from":0,"size":10,"sort":{"insertDate":"desc"},"query":{"bool":{"must":[{"range":
{"insertDate":{"gte":"2020-01-31T21:00:00.000Z","lt":"now"}}},{"query_string":{"query":"123456",
"fields":["requestId""type","authSource","ip","statusMessage","serviceId","serviceName","username","userId","gatewayId","gatewayName",,"networkId","networkName"]}}]}}}


###


POST http://192.168.88.51:9200/ferrumgate-activity-*/_search
Authorization: Basic ZWxhc3RpYzp1eDRleXJrYnI0N3o2c2NreWY5em1hdnZnenhndnJ6ZWJzaDA4MmR1bWZrNTlqM2I1dGk5ZnZ5OTVzN3N5Ym14
Content-Type: application/json

{
    "size":10,
        "sort": {
        "insertDate": "asc"
    },
    "query": {
        "bool": {
            "must": [
                {
                    "range": {
                        "insertDate": {
                            "gte": "2022-11-27T00:00:00.000Z",
                            "lt": "2022-12-03T22:53:58.954Z"
                        }
                    }
                },
                {                            
                                "term": {
                                    "type": "login try"
                                }                 
                        
                    
                }
            ],
             "must_not": [
            ]
        }
    },
     "aggs": {
        "insertDate": {
      "date_histogram": {
        "field": "insertDate",
        "calendar_interval": "day",
        "min_doc_count": 0,
        "extended_bounds": { "min": "2022-11-27T00:00:00.000Z", "max": "2022-12-04T23:59:00.000Z" }
      },
      "aggs":{
        "status": {
      "terms": {
        "field": "status"
      }
    }
      }
    }
    
  }
}



####

POST http://192.168.88.51:9200/ferrumgate-activity-*/_search
Authorization: Basic ZWxhc3RpYzp1eDRleXJrYnI0N3o2c2NreWY5em1hdnZnenhndnJ6ZWJzaDA4MmR1bWZrNTlqM2I1dGk5ZnZ5OTVzN3N5Ym14
Content-Type: application/json

{
    "size":10,
        "sort": {
        "insertDate": "asc"
    },
    "query": {
        "bool": {
            "must": [
                {
                    "range": {
                        "insertDate": {
                            "gte": "2022-12-01T22:03:04.000Z",
                            "lt": "2022-12-04T16:53:58.954Z"
                        }
                    }
                },
                {                            
                                "term": {
                                    "type": "create tunnel"
                                }                 
                        
                    
                }
            ],
             "must_not": [
            ]
        }
    },
     "aggs": {
        "insertDate": {
      "date_histogram": {
        "field": "insertDate",
        "calendar_interval": "day",
        "min_doc_count": 0,
        "extended_bounds": { "min": "2022-12-01T22:03:04.000Z", "max": "2022-12-04T16:53:58.954Z" }
      },
      "aggs":{
        "tunType": {
      "terms": {
        "field": "tunType"
      }
    }
      }
    }
    
  }
}


####

POST http://192.168.88.51:9200/ferrumgate-activity-*/_search
Authorization: Basic ZWxhc3RpYzp1eDRleXJrYnI0N3o2c2NreWY5em1hdnZnenhndnJ6ZWJzaDA4MmR1bWZrNTlqM2I1dGk5ZnZ5OTVzN3N5Ym14
Content-Type: application/json

{
    "size": 0,
    "query": {
        "bool": {
            "must": [
                {
                    "range": {
                        "insertDate": {
                            "gte": "2022-11-27T00:00:00.000Z",
                            "lt": "2022-12-04T22:53:58.954Z"
                        }
                    }
                },
                {
                    "term": {
                        "type": "login try"
                    }
                },
                {
                    "term": {
                        "status": 200
                    }
                }
            ],
            "must_not": []
        }
    },
     "aggs": {
                "username": {
                    "terms": {
                        "field": "username",
                        "size": 1,
                        "order":{
                            "_count":"asc"
                        }
                        
                    }
                }
            }

}


####

POST http://192.168.88.51:9200/ferrumgate-activity-*/_search
Authorization: Basic ZWxhc3RpYzp1eDRleXJrYnI0N3o2c2NreWY5em1hdnZnenhndnJ6ZWJzaDA4MmR1bWZrNTlqM2I1dGk5ZnZ5OTVzN3N5Ym14
Content-Type: application/json

{
    "size":10,
        "sort": {
        "insertDate": "asc"
    },
    "query": {
        "bool": {
            "must": [
                {
                    "range": {
                        "insertDate": {
                            "gte": "2022-11-27T00:00:00.000Z",
                            "lt": "2022-12-06T22:53:58.954Z"
                        }
                    }
                },
                {                            
                                "term": {
                                    "type": "login try"
                                }                 
                        
                    
                },
                 {                            
                                "term": {
                                    "username": "hamza@hamzakilic.com"
                                }                 
                        
                    
                }
            ],
             "must_not": [
            ]
        }
    },
     "aggs": {
        "insertDate": {
      "date_histogram": {
        "field": "insertDate",
        "calendar_interval": "day",
        "min_doc_count": 0,
        "extended_bounds": { "min": "2022-11-27T00:00:00.000Z", "max": "2022-12-06T23:59:00.000Z" }
      },
      "aggs":{
        "status": {
      "terms": {
        "field": "status"
      }
    }
      }
    }
    
  }
}

####

POST http://192.168.88.51:9200/ferrumgate-activity-*/_search
Authorization: Basic ZWxhc3RpYzp1eDRleXJrYnI0N3o2c2NreWY5em1hdnZnenhndnJ6ZWJzaDA4MmR1bWZrNTlqM2I1dGk5ZnZ5OTVzN3N5Ym14
Content-Type: application/json

{
    "size":10,
        "sort": {
        "insertDate": "asc"
    },
    "query": {
        "bool": {
            "must": [
                {
                    "range": {
                        "insertDate": {
                            "gte": "2022-11-27T00:00:00.000Z",
                            "lt": "2022-12-06T22:53:58.954Z"
                        }
                    }
                },
                {                            
                                "term": {
                                    "type": "login try"
                                }                 
                        
                    
                },
                 {                            
                                "term": {
                                    "username": "hamza@hamzakilic.com"
                                }                 
                        
                    
                }
            ],
             "must_not": [
            ]
        }
    },
     "aggs": {
        "insertDate": {
      "date_histogram": {
        "field": "insertDate",
        "calendar_interval": "hour",
        "min_doc_count": 0,
        "extended_bounds": { "min": "2022-11-27T00:00:00.000Z", "max": "2022-12-06T23:59:00.000Z" }
      },
      "aggs":{
        "status": {
      "terms": {
        "field": "status"
      }
    }
      }
    }
    
  }
}

